### ISSUE TITLE
Support for webp in php71u-gd

### ISSUE THREAD

**Issue by berndDC** [iuscommunity-pkg/php71u#10]
We are running CentOS 6.x and CentOS 7.x with php70u and like to update to php71u

**webp** support is **missing** in **php71u**

### Output php70u
```
[root:~] # php --version
PHP 7.0.22 (cli) (built: Aug  7 2017 16:18:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22, Copyright (c) 1999-2017, by Zend Technologies

[root:~] # php --ri gd
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.3.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.2.49
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 0 => 0
```

### Output php71u
```
[root:~] 40s # php --version
PHP 7.1.8 (cli) (built: Aug  7 2017 13:46:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies

[root:~] 40s # php --ri gd
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.3.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.2.49
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```
### Question
Why is **webp** not enabled by default in **php71u**?

**Comment by carlwgeorge** [comment]
Hello @berndDC.  I've been looking into this for a bit, and it seemed a bit strange since in both cases we are using the copy of GD that is bundled with the PHP source.  But I did discover one of the php70u configure flags was missing from php71u, so I [added it to php71u](https://github.com/iuscommunity-pkg/php71u/commit/d3a65d692bd313f74166a417c7c0a170831d63a5).  This appears to have resolved the issue.  Please check out [7.1.9-2](https://github.com/iuscommunity-pkg/php71u/releases/tag/7.1.9-2) after it moves to our testing repo during tonight's automation.

**Comment by berndDC** [comment]
Hi @carlwgeorge 

I've installed 7.1.9-2 and so far no problems reported from our dev-team.

Thank you.

**Comment by carlwgeorge** [comment]
Thanks for the confirmation.  We'll proceed with publishing this update to the stable repos.  Thanks for participating in IUS!
