### ISSUE TITLE
Opcache huge_code_pages errors on CentOS6

### ISSUE THREAD

**Issue by BPScott** [iuscommunity-pkg/php71u#2]
I am running CentOS6, have installed `php71u` and `php71u-opcache` and am getting the following warning when running a PHP script:

```
PHP Warning:  Zend OPcache huge_code_pages: mmap(HUGETLB) failed: Cannot allocate memory (12) in Unknown on line 0
```

After a bit of internet spelunking I think the root cause is thus:

Opcache has a config option called `huge_code_pages` that lets you take advantage of huge page sizes. This is now [enabled by default in php71u](https://github.com/iuscommunity-pkg/php71u/blob/a91a6655bb5c18b1c83fced6c5a89c9a4638967c/SOURCES/10-opcache.ini#L120-L122). In [php70u this was disabled by default](https://github.com/iuscommunity-pkg/php70u/blob/a59ce11a534047806627797d2dc7e2b3742d7b1a/SOURCES/opcache.ini#L109-L111) so it never cropped up before.

It turns out that [CentOS6 doesn't support huge code pages](https://forum.remirepo.net/viewtopic.php?id=3335). So thus can this config line be removed for CentOS6 RPMs? Commenting out the `opcache.huge_code_pages=1` config line stops the warning from appearing.

As usual, @remicollet knows many things and has dealt with this in his repos already: https://github.com/remicollet/remirepo/commit/27702c4f0fa479e00926369501b0f6d63c95fac3

**Comment by remicollet** [comment]
> As usual, @remicollet knows many things and has dealt with this in his repos already

;)

So, you know what repo you should use

**Comment by carlwgeorge** [comment]
Howdy @BPScott,

Thanks for bringing this to our attention.  We fork our spec files from Fedora.  At the time we created php70u, the [Rawhide spec file was still on 5.6](https://src.fedoraproject.org/cgit/rpms/php.git/commit/?id=2261b4f) and had no mention of the opcache.huge_code_pages setting in opcache.ini.  I [updated our opcache.ini file](https://github.com/iuscommunity-pkg/php70u/commit/134212ccd8d631bb8f39fe1b01aa296f8e8c7e3c#diff-7ab37d291645911133a26f6a1957a648) based on the upstream [php.ini-production example file](https://github.com/php/php-src/blob/php-7.0.0/php.ini-production) (which had that setting [commented out](https://github.com/php/php-src/blob/php-7.0.0/php.ini-production#L1843-L1845)).  As of [7.0.14 it is still commented out](https://github.com/php/php-src/blob/PHP-7.0.14/php.ini-production#L1882-L1884).

When we forked our php71u spec file, Rawhide was up to date and had that setting [explicitly disabled](https://src.fedoraproject.org/cgit/rpms/php.git/tree/10-opcache.ini?id=36adeed#n122) in the ini file, but then [flips the 0 to a 1 in the spec file](https://src.fedoraproject.org/cgit/rpms/php.git/tree/php.spec?id=36adeed#n829) during the build if on x86_64 hardware.  That's how it is currently enabled in our EL6 (x86_64) packages.  As of [7.1.0 it is still commented out](https://github.com/php/php-src/blob/PHP-7.1.0/php.ini-production#L1897-L1899) in the upstream example file.

IUS stands for **I**nline with **U**pstream **S**table.  We consider both the upstream project and Fedora as upstream for our packages.  Since upstream and Fedora are doing different things, we have to make a choice.

* disable opcache.huge_code_pages everywhere (upstream recommendation)
* enable opcache.huge_code_pages when possible (Fedora setting, would result in just enabling it on EL7 x86_64)

Which sounds better to you?

**Comment by BPScott** [comment]
Thanks for the Fedora repo links @carlwgeorge, I had knew IUS tracked the Fedora specs but I wasn't confident on where Fedora kept its repo and I wasn't sure if this issue was better targeted here or to Fedora.

Both options are acceptable, I guess it comes down to who IUS considers to be the more canonical upstream.

My gut reckons tracking Fedora behaviour is preferable. If Fedora thinks the option is stable enough to use then following their lead in enabling opcache.huge_code_pages when possible sounds like a preferable option over a blanket disabling.

Should this issue also be raised to whomever maintains the Fedora repo too? I don't know is supporting RHEL6 is relevant to them.

**Comment by carlwgeorge** [comment]
Remi is the primary package maintainer of php in both Fedora and in RHEL (he is a Red Hat employee), but I can already tell you that maintaining EL6 compatibility in the Fedora spec file is not a priority.  For example, they removed their sysvinit conditionals quite some time ago.

If you think that enabling it when possible is the best choice, do you think it's worth making the same change in php70u to match?

**Comment by BPScott** [comment]
Keeping php70u and php71u consistent does sound useful from the principle of least surprise, assuming it's a small amount of work.

It doesn't look like [the code relating to the toggle](https://github.com/php/php-src/blob/669f0b39b184593e01e677360fd79b2b63058ca0/ext/opcache/ZendAccelerator.c) has been updated since 7.0.1 so backporting at this point does sound feasible.

Personally I have no immediate plans to upgrade away from CentOS6 so this wouldn't affect me either way.

**Comment by carlwgeorge** [comment]
So I dug into this a bit more, and I was able to reproduce that warning on a CentOS 6 cloud server.

```
[root@test6 ~]# service php-fpm start
Starting php-fpm: [23-Dec-2016 18:00:15] NOTICE: PHP message: PHP Warning:  Zend OPcache huge_code_pages: mmap(HUGETLB) failed: Cannot allocate memory (12) in Unknown on line 0
                                                           [  OK  ]
[root@test6 ~]# service php-fpm stop
Stopping php-fpm:                                          [  OK  ]
```

However, the [RHEL 6 documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Performance_Tuning_Guide/s-memory-transhuge.html) indicates that EL6 _does_ support huge pages, but the default value is 0 pages (disabled).

```
[root@test6 ~]# sysctl vm.nr_hugepages 
vm.nr_hugepages = 0
[root@test6 ~]# grep Huge /proc/meminfo 
AnonHugePages:      2048 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

After enabling some huge pages, php-fpm starts without issue.  I can even observe that it allocated a huge page.

```
[root@test6 ~]# sysctl -w vm.nr_hugepages=4
vm.nr_hugepages = 4
[root@test6 ~]# grep Huge /proc/meminfo 
AnonHugePages:      2048 kB
HugePages_Total:       4
HugePages_Free:        4
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
[root@test6 ~]# service php-fpm start
Starting php-fpm:                                          [  OK  ]
[root@test6 ~]# grep Huge /proc/meminfo 
AnonHugePages:     14336 kB
HugePages_Total:       4
HugePages_Free:        3
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

It's worth emphasizing that the upstream example php.ini file states that the opcache.huge_code_pages setting "requires appropriate OS configuration".  It seems like to me the best option is to build with huge page support (no `--disable-huge-code-pages` build flag) but leave it disabled in the configuration file for both EL6 and EL7.

P.S. Strangely enough, [opcache.huge_code_pages isn't even documented in the PHP manual](http://php.net/manual/en/opcache.configuration.php).

**Comment by carlwgeorge** [comment]
I've made [the change](https://github.com/iuscommunity-pkg/php71u/commit/9e0eed6231909fefefb8a8a715b0a604fcc07743), and it will be available in [7.1.0-3](https://github.com/iuscommunity-pkg/php71u/releases/7.1.0-3), which should move to the testing repositories during tonight's automation.

**Comment by BPScott** [comment]
Thanks for your work on this @carlwgeorge. I see is in the 7.1.0-3 in the testing repo, I don't suppose you've got an ETA of when you're hoping to push this to stable?

**Comment by carlwgeorge** [comment]
Typically we leave our packages in the testing repositories for two weeks before promoting them to stable.  That will be Saturday, but we don't push packages on the weekend, so probably Monday.  However, if you have installed 7.1.0-3 from testing and can confirm the fix works as expected, I can queue it up to be promoted during tonight's automation.

**Comment by BPScott** [comment]
I've installed 7.1.0-3 from testing and can confirm that it works and the warning message is gone. No need to divert from your standard release process just for me though. I'm happy to wait till Monday.

**Comment by b-harper** [comment]
@BPScott, thanks for the feedback.  The updated packages will get pushed to the stable repositories during tonight's automation run.

**Comment by BPScott** [comment]
Going above and beyond. Thanks @b-harper <3
